parser: babel-eslint
env:
  browser: true
  node: true
globals:
  wx: true
  canvas: true
  PIXI: true
extends:
- eslint:recommended
- plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
- react
rules:
  no-unused-vars: 1
  react/display-name: 0
  react/prop-types: 0
settings:
  react:
    version: latest
